/**
 * Seed data for development — sample packs for the marketplace.
 * Run with: npx tsx src/lib/db/seed.ts
 */

export const SEED_USER = {
  id: "seed-user-1",
  email: "creator@promptkit.dev",
  name: "PromptKit Team",
  image: null,
  bio: "The official PromptKit team — building interactive widgets for vibe coding",
  role: "creator",
}

export const SEED_PACKS = [
  {
    id: "pack-tailwind",
    slug: "tailwind-essentials",
    name: "Tailwind Essentials",
    description: "All Tailwind CSS design tokens as interactive widgets — colors, spacing, breakpoints, shadows, and more. Drop exact Tailwind classes into your prompts.",
    version: "1.0.0",
    category: "components",
    tags: ["tailwind", "css", "design-tokens", "utility-first"],
    priceCents: 0,
    iconUrl: null,
    widgetCount: 24,
    widgetTypes: ["tw-color", "tw-spacing", "tw-font", "tw-shadow", "tw-border", "tw-radius", "tw-breakpoint", "tw-container"],
    downloads: 2847,
    status: "published",
    npmPackage: "@promptkit/pack-tailwind",
    readme: "# Tailwind Essentials\n\nDrop Tailwind design tokens directly into your prompts. Every widget maps to exact Tailwind classes.\n\n## Widgets\n- **Colors**: All 22 Tailwind color scales (50-950)\n- **Spacing**: 0-96 scale\n- **Typography**: Font sizes, weights, families\n- **Shadows**: shadow-sm to shadow-2xl\n- **Borders**: widths, radii, colors\n- **Breakpoints**: sm, md, lg, xl, 2xl\n\n## Install\n```bash\nnpm install @promptkit/pack-tailwind\n```",
    manifest: { name: "tailwind-essentials", version: "1.0.0", widgets: [] },
  },
  {
    id: "pack-magicui",
    slug: "magicui-effects",
    name: "MagicUI Effects",
    description: "Stunning visual effects from MagicUI — shimmer buttons, animated gradients, sparkles, meteors, and 30+ animated components ready to drop into prompts.",
    version: "1.2.0",
    category: "effects",
    tags: ["magicui", "animation", "effects", "shimmer", "sparkles", "gradient"],
    priceCents: 0,
    iconUrl: null,
    widgetCount: 32,
    widgetTypes: ["shimmer-button", "rainbow-button", "border-beam", "sparkles", "particles", "meteors", "marquee", "animated-beam"],
    downloads: 5213,
    status: "published",
    npmPackage: "@promptkit/pack-magicui",
    readme: "# MagicUI Effects\n\nAll the magic of MagicUI, now as interactive widgets.\n\n## Install\n```bash\nnpm install @promptkit/pack-magicui\n```",
    manifest: { name: "magicui-effects", version: "1.2.0", widgets: [] },
  },
  {
    id: "pack-aceternity",
    slug: "aceternity-ui",
    name: "Aceternity UI",
    description: "Premium Aceternity UI components as widgets — aurora backgrounds, spotlights, 3D cards, floating navbars, parallax scrolling, and more.",
    version: "1.0.0",
    category: "components",
    tags: ["aceternity", "3d", "parallax", "aurora", "premium", "backgrounds"],
    priceCents: 500,
    iconUrl: null,
    widgetCount: 18,
    widgetTypes: ["aurora-bg", "spotlight", "3d-card", "floating-nav", "parallax-scroll", "wavy-bg", "tracing-beam"],
    downloads: 1832,
    status: "published",
    npmPackage: "@promptkit/pack-aceternity",
    readme: "# Aceternity UI Pack\n\nPremium Aceternity components.\n\n## Install\n```bash\nnpm install @promptkit/pack-aceternity\n```",
    manifest: { name: "aceternity-ui", version: "1.0.0", widgets: [] },
  },
  {
    id: "pack-threejs",
    slug: "3d-scenes",
    name: "3D Scenes",
    description: "Drop Three.js scenes, materials, lighting, and camera angles into your prompts. Perfect for 3D web experiences with React Three Fiber.",
    version: "0.9.0",
    category: "components",
    tags: ["threejs", "3d", "r3f", "webgl", "materials", "lighting"],
    priceCents: 800,
    iconUrl: null,
    widgetCount: 15,
    widgetTypes: ["scene-preset", "material", "lighting", "camera-angle", "geometry", "animation-3d"],
    downloads: 943,
    status: "published",
    npmPackage: "@promptkit/pack-threejs",
    readme: "# 3D Scenes\n\nThree.js + React Three Fiber widgets.\n\n## Install\n```bash\nnpm install @promptkit/pack-threejs\n```",
    manifest: { name: "3d-scenes", version: "0.9.0", widgets: [] },
  },
  {
    id: "pack-motion",
    slug: "motion-presets",
    name: "Motion Presets",
    description: "120+ animation presets for Framer Motion — enter/exit transitions, scroll animations, gesture responses, layout animations, and spring configs.",
    version: "2.0.0",
    category: "effects",
    tags: ["framer-motion", "animation", "transitions", "spring", "gestures"],
    priceCents: 0,
    iconUrl: null,
    widgetCount: 45,
    widgetTypes: ["enter-anim", "exit-anim", "scroll-anim", "gesture", "spring-config", "layout-anim", "stagger"],
    downloads: 3421,
    status: "published",
    npmPackage: "@promptkit/pack-motion",
    readme: "# Motion Presets\n\n120+ Framer Motion animations.\n\n## Install\n```bash\nnpm install @promptkit/pack-motion\n```",
    manifest: { name: "motion-presets", version: "2.0.0", widgets: [] },
  },
  {
    id: "pack-ecommerce",
    slug: "ecommerce-ui",
    name: "E-Commerce UI",
    description: "Product cards, pricing tables, checkout flows, cart widgets, review stars, and conversion-optimized components for online stores.",
    version: "1.1.0",
    category: "components",
    tags: ["ecommerce", "shopping", "pricing", "checkout", "product-card"],
    priceCents: 1000,
    iconUrl: null,
    widgetCount: 22,
    widgetTypes: ["product-card", "pricing-table", "checkout-step", "cart-item", "review-stars", "badge", "countdown"],
    downloads: 1567,
    status: "published",
    npmPackage: "@promptkit/pack-ecommerce",
    readme: "# E-Commerce UI\n\nConversion-optimized components.\n\n## Install\n```bash\nnpm install @promptkit/pack-ecommerce\n```",
    manifest: { name: "ecommerce-ui", version: "1.1.0", widgets: [] },
  },
  {
    id: "pack-dashboard",
    slug: "dashboard-kit",
    name: "Dashboard Kit",
    description: "Charts, KPI cards, data tables, stat widgets, progress bars, and dashboard layout patterns. Built for admin panels and analytics dashboards.",
    version: "1.0.0",
    category: "components",
    tags: ["dashboard", "charts", "analytics", "data-viz", "admin", "tables"],
    priceCents: 0,
    iconUrl: null,
    widgetCount: 28,
    widgetTypes: ["chart-type", "kpi-card", "data-table", "stat-widget", "progress", "sparkline", "heatmap"],
    downloads: 4102,
    status: "published",
    npmPackage: "@promptkit/pack-dashboard",
    readme: "# Dashboard Kit\n\nEverything for admin dashboards.\n\n## Install\n```bash\nnpm install @promptkit/pack-dashboard\n```",
    manifest: { name: "dashboard-kit", version: "1.0.0", widgets: [] },
  },
  {
    id: "pack-accessibility",
    slug: "a11y-toolkit",
    name: "Accessibility Toolkit",
    description: "WCAG-compliant widgets — contrast checker, focus indicators, ARIA roles, screen reader hints, reduced motion presets, and color-blind safe palettes.",
    version: "1.0.0",
    category: "logic",
    tags: ["accessibility", "a11y", "wcag", "aria", "contrast", "screen-reader"],
    priceCents: 0,
    iconUrl: null,
    widgetCount: 12,
    widgetTypes: ["contrast-check", "focus-style", "aria-role", "sr-hint", "reduced-motion", "color-safe"],
    downloads: 2189,
    status: "published",
    npmPackage: "@promptkit/pack-a11y",
    readme: "# Accessibility Toolkit\n\nWCAG compliance made easy.\n\n## Install\n```bash\nnpm install @promptkit/pack-a11y\n```",
    manifest: { name: "a11y-toolkit", version: "1.0.0", widgets: [] },
  },
]
